/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Rajat
 */
public class Loginpage extends javax.swing.JFrame {

    /**
     * Creates new form Loginpage
     */
    public Loginpage() {
        initComponents();
        this.setSize(500,400);
        ImageIcon img=new ImageIcon(getClass().getResource("/form/pizza1.jpg"));
        Image img1=img.getImage();
        Image img2=img1.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_FAST);
        ImageIcon img3=new ImageIcon(img2);
        jLabel1.setSize(this.getWidth(),this.getHeight());
        jLabel1.setIcon(img3);
        jLabel2.setLocation((this.getWidth()-jLabel2.getWidth())/2, 20);
            jLabel3.setLocation((this.getWidth()-jLabel3.getWidth())/2-90, 100);
                jLabel4.setLocation((this.getWidth()-jLabel4.getWidth())/2-90, 140);
                jTextField1.setLocation((this.getWidth()-jTextField1.getWidth())/2+20, 100);
                jTextField2.setLocation((this.getWidth()-jTextField2.getWidth())/2+20, 140);
                jButton1.setLocation((this.getWidth()-jButton1.getWidth())/2, 210);
                jButton2.setLocation((this.getWidth()-jButton2.getWidth())/2, 260);
                jCheckBox1.setLocation((this.getWidth()-jCheckBox1.getWidth())/2+20, 170);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                jb(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("Employee Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 193, 130, 40);

        jButton2.setText("Manager Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 250, 130, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Form");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 50, 230, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 110, 80, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 150, 70, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 100, 140, 30);

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(210, 180, 130, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 150, 140, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jb
        // TODO add your handling code here:
        ImageIcon img=new ImageIcon(getClass().getResource("/form/pizza1.jpg"));
        Image img1=img.getImage();
        Image img2=img1.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_FAST);
        ImageIcon img3=new ImageIcon(img2);
        jLabel1.setSize(this.getWidth(),this.getHeight());
        jLabel1.setIcon(img3);
        jLabel2.setLocation((this.getWidth()-jLabel2.getWidth())/2, this.getHeight()/8);
            jLabel3.setLocation((this.getWidth()-jLabel3.getWidth())/2-90, this.getHeight()/8+70);
                jLabel4.setLocation((this.getWidth()-jLabel4.getWidth())/2-90, this.getHeight()/8+110);
                jTextField1.setLocation((this.getWidth()-jTextField1.getWidth())/2+20, this.getHeight()/8+70);
                jTextField2.setLocation((this.getWidth()-jTextField2.getWidth())/2+20, this.getHeight()/8+110);
                jButton1.setLocation((this.getWidth()-jButton1.getWidth())/2, this.getHeight()/8+180);
                jButton2.setLocation((this.getWidth()-jButton2.getWidth())/2, this.getHeight()/8+230);
                jCheckBox1.setLocation((this.getWidth()-jCheckBox1.getWidth())/2+20, this.getHeight()/8+140);
       // jPanel1.setLocation((this.getWidth()-jPanel1.getWidth())/2, (this.getHeight()-jPanel1.getHeight())/2);
        //jLabel3.setLocation((this.getWidth()-jLabel3.getWidth())/2, 100);
    }//GEN-LAST:event_jb

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            jTextField2.setEchoChar((char)0);
        }
        else {
            jTextField2.setEchoChar('*');

        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        if(s1.equals("jatin")&&s2.equals("bansal")){
            pizza_main m1=new pizza_main();
            m1.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"username or password is incorrect");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        if(s1.equals("jatin")&&s2.equals("bansal")){
            manager_login m1=new manager_login();
            m1.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"username or password is incorrect");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    // End of variables declaration//GEN-END:variables
}
